# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/setup/steps.yaml
FirstInstance:
  Org:
    Human:
      # use the loginname root@zitadel.localhost, replace localhost with your configured external domain
      Username: 'root'
      # First login requires password change. 
      Password: 'Password1!'
      
      Email:
        # Optional, if set, can be used to log in with email.
        Address: 'example@zitadel.com' # ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_ADDRESS    
